#!/bin/bash

type="$1"
shift

help(){
# Instructions
# Script command : send help
#
echo 'Usage:

send message "text"
    Sends a text message to the recipient.

send image "path to image"
    Sends an image without compression.

send url "https://example.com"
    Sends a clickable URL.

send file "path to file"
    Sends a file as an attachment.'
}

case "$type" in
    help)
        # Instructions
        help
      ;;
    message)
        "/usr/bin/telegramSendMessage" message "$*"
        ;;
    img)
        "/usr/bin/telegramSendMessage" img "$(pwd)/$*"
        ;;
    url)
        "/usr/bin/telegramSendMessage" url "$*"
        ;;
    file)
        "/usr/bin/telegramSendMessage" file "$(pwd)/$*"
        ;;
    *)
    # Exit zone
    #
    echo "send: bad usage"
    echo "Try 'send help' for more information."
    exit 1
    ;;
esac
